CREATE TABLE [dbo].[Account_201605131815] (
    [Id]                        CHAR (36)       NOT NULL,
    [Ageing_Less30]             DECIMAL (19, 5) NULL,
    [Ageing_Less60]             DECIMAL (19, 5) NULL,
    [Ageing_Less90]             DECIMAL (19, 5) NULL,
    [Ageing_Less120]            DECIMAL (19, 5) NULL,
    [Ageing_Less365]            DECIMAL (19, 5) NULL,
    [Ageing_More365]            DECIMAL (19, 5) NULL,
    [AccountNo]                 VARCHAR (4000)  NULL,
    [AppliedOn]                 VARCHAR (27)    NULL,
    [CreatedOn]                 VARCHAR (27)    NULL,
    [UpdatedOn]                 VARCHAR (27)    NULL,
    [UpdatedById]               CHAR (36)       NULL,
    [UpdatedByName]             VARCHAR (4000)  NULL,
    [RegistrationId]            CHAR (36)       NULL,
    [VirtualBankAccountNo]      VARCHAR (4000)  NULL,
    [ActivationCode]            VARCHAR (4000)  NULL,
    [Category]                  INT             NULL,
    [AccountType]               INT             NULL,
    [SubAccountType]            INT             NULL,
    [MasterAccountId]           CHAR (36)       NULL,
    [GroupId]                   CHAR (36)       NULL,
    [MasterAccountNo]           VARCHAR (4000)  NULL,
    [MasterAccountName]         VARCHAR (4000)  NULL,
    [IsTempAccount]             TINYINT         NULL,
    [TempAccountExpiry]         VARCHAR (27)    NULL,
    [Status]                    INT             NULL,
    [TerminationReason]         VARCHAR (4000)  NULL,
    [TerminationFileId]         VARCHAR (4000)  NULL,
    [TerminatedOn]              VARCHAR (27)    NULL,
    [ReasonId]                  CHAR (36)       NULL,
    [BillingType]               INT             NULL,
    [BillingCycle]              INT             NULL,
    [BillingDay]                INT             NULL,
    [BillingMonth]              INT             NULL,
    [IsTaxExempted]             TINYINT         NULL,
    [LastPaymentDate]           VARCHAR (27)    NULL,
    [LastBillingDate]           VARCHAR (27)    NULL,
    [NextBillingDate]           VARCHAR (27)    NULL,
    [CreditLimit]               DECIMAL (19, 5) NULL,
    [CreditOfficerId]           CHAR (36)       NULL,
    [CreditOfficerName]         VARCHAR (4000)  NULL,
    [Name]                      VARCHAR (4000)  NULL,
    [RocNo]                     VARCHAR (4000)  NULL,
    [CompanyType]               INT             NULL,
    [IndustryId]                CHAR (36)       NULL,
    [IsPostingDomestic]         TINYINT         NULL,
    [IsPostingInternational]    TINYINT         NULL,
    [IsAgent]                   TINYINT         NULL,
    [AddressStreet1]            VARCHAR (4000)  NULL,
    [AddressStreet2]            VARCHAR (4000)  NULL,
    [AddressStreet3]            VARCHAR (4000)  NULL,
    [AddressPostCode]           VARCHAR (4000)  NULL,
    [AddressCity]               VARCHAR (4000)  NULL,
    [AddressStateName]          VARCHAR (4000)  NULL,
    [AddressCountryName]        VARCHAR (4000)  NULL,
    [AddressStateId]            CHAR (36)       NULL,
    [AddressCountryId]          CHAR (36)       NULL,
    [ContactName]               VARCHAR (4000)  NULL,
    [ContactNric]               VARCHAR (4000)  NULL,
    [ContactEmail]              VARCHAR (4000)  NULL,
    [PhoneNo]                   VARCHAR (4000)  NULL,
    [FaxNo]                     VARCHAR (4000)  NULL,
    [BillingAddressSame]        TINYINT         NULL,
    [BillingAddressStreet1]     VARCHAR (4000)  NULL,
    [BillingAddressStreet2]     VARCHAR (4000)  NULL,
    [BillingAddressStreet3]     VARCHAR (4000)  NULL,
    [BillingAddressPostCode]    VARCHAR (4000)  NULL,
    [BillingAddressCity]        VARCHAR (4000)  NULL,
    [BillingAddressStateName]   VARCHAR (4000)  NULL,
    [BillingAddressCountryName] VARCHAR (4000)  NULL,
    [BillingAddressStateId]     CHAR (36)       NULL,
    [BillingAddressCountryId]   CHAR (36)       NULL,
    [BillingCurrencyId]         CHAR (36)       NULL,
    [BillingCurrencyName]       VARCHAR (4000)  NULL,
    [BranchId]                  CHAR (36)       NULL,
    [BranchCode]                VARCHAR (4000)  NULL,
    [SalesPersonnelId]          CHAR (36)       NULL,
    [SalesPersonnelName]        VARCHAR (4000)  NULL,
    [SbuId]                     CHAR (36)       NULL,
    [SbuName]                   VARCHAR (4000)  NULL,
    [SbuAccountType]            VARCHAR (4000)  NULL,
    [CompanyIsBlackListed]      TINYINT         NULL,
    [CompanyIsCtosListed]       TINYINT         NULL,
    [IsIncludedRebate]          TINYINT         NULL,
    [DepositAmount]             DECIMAL (19, 5) NULL,
    [CreditOfficerEmail]        VARCHAR (4000)  NULL,
    [CreditOfficerPhoneNo]      VARCHAR (4000)  NULL,
    [CreditOfficerFaxNo]        VARCHAR (4000)  NULL,
    [Name2]                     VARCHAR (4000)  NULL,
    [AddressStreet4]            VARCHAR (4000)  NULL,
    [AddressStreet5]            VARCHAR (4000)  NULL,
    [AddressStateCode]          VARCHAR (4000)  NULL,
    [AddressCountryCode]        VARCHAR (4000)  NULL,
    [BillingAddressStreet4]     VARCHAR (4000)  NULL,
    [BillingAddressStreet5]     VARCHAR (4000)  NULL,
    [BillingAddressStateCode]   VARCHAR (4000)  NULL,
    [BillingAddressCountryCode] VARCHAR (4000)  NULL
);

