CREATE TABLE [dbo].[Bill] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [SerializedDiscounts] NVARCHAR (4000)  NULL,
    [SerializedRebates]   NVARCHAR (4000)  NULL,
    [BillDate]            DATETIME2 (7)    NULL,
    [AccountId]           UNIQUEIDENTIFIER NULL,
    [AccountNo]           NVARCHAR (4000)  NULL,
    [AccountName]         NVARCHAR (4000)  NULL,
    [InvoiceId]           UNIQUEIDENTIFIER NULL,
    [InvoiceNo]           NVARCHAR (4000)  NULL,
    [InvoiceAmount]       DECIMAL (19, 5)  NULL,
    [CreditMemoAmount]    DECIMAL (19, 5)  NULL,
    [DebitMemoAmount]     DECIMAL (19, 5)  NULL,
    [DiscountAmount]      DECIMAL (19, 5)  NULL,
    [RebateAmount]        DECIMAL (19, 5)  NULL,
    [NetAmount]           DECIMAL (19, 5)  NULL,
    [CycleFrom]           DATETIME2 (7)    NULL,
    [CycleTo]             DATETIME2 (7)    NULL,
    [Street1]             NVARCHAR (4000)  NULL,
    [Street2]             NVARCHAR (4000)  NULL,
    [Street3]             NVARCHAR (4000)  NULL,
    [PostCode]            NVARCHAR (4000)  NULL,
    [City]                NVARCHAR (4000)  NULL,
    [StateId]             UNIQUEIDENTIFIER NULL,
    [StateName]           NVARCHAR (4000)  NULL,
    [CountryId]           UNIQUEIDENTIFIER NULL,
    [CountryName]         NVARCHAR (4000)  NULL,
    [IsCompleted]         BIT              NULL,
    [IsManual]            BIT              NULL,
    [CreatedById]         UNIQUEIDENTIFIER NULL,
    [CreatedByName]       NVARCHAR (4000)  NULL,
    [CreatedOn]           DATETIME2 (7)    NULL,
    [PostingStatus]       TINYINT          NOT NULL,
    [ProfitCenterCode]    NVARCHAR (4000)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

