CREATE TABLE [dbo].[Compensation] (
    [Id]                                UNIQUEIDENTIFIER NOT NULL,
    [BillBack_GTM]                      BIT              NULL,
    [BillBack_IBSAX]                    BIT              NULL,
    [BillBack_IBSPMIH]                  BIT              NULL,
    [BillBack_SCS]                      BIT              NULL,
    [BillBack_CDS]                      BIT              NULL,
    [BillBack_OSS]                      BIT              NULL,
    [BillBack_ForeignPosterPartner]     BIT              NULL,
    [BillBack_ForeignPosterPartnerId]   UNIQUEIDENTIFIER NULL,
    [BillBack_ForeignPosterPartnerName] NVARCHAR (4000)  NULL,
    [BillBack_Insurances]               BIT              NULL,
    [BillBack_Others]                   BIT              NULL,
    [BillBack_OthersName]               NVARCHAR (4000)  NULL,
    [ProposedAmount]                    DECIMAL (19, 5)  NULL,
    [Fee]                               DECIMAL (19, 5)  NULL,
    [SbaSp]                             DECIMAL (19, 5)  NULL,
    [TotalCompensation]                 DECIMAL (19, 5)  NULL,
    [Finding]                           NVARCHAR (4000)  NULL,
    [Resolution]                        NVARCHAR (4000)  NULL,
    [IsProposedRejection]               BIT              NULL,
    [RejectionReason]                   NVARCHAR (4000)  NULL,
    [Stage]                             INT              NULL,
    [Pending]                           INT              NULL,
    [Approval]                          INT              NULL,
    [CreatedById]                       UNIQUEIDENTIFIER NULL,
    [CreatedByName]                     NVARCHAR (4000)  NULL,
    [CreatedOn]                         DATETIME2 (7)    NULL,
    [UpdatedOn]                         DATETIME2 (7)    NULL,
    [SbuId]                             UNIQUEIDENTIFIER NULL,
    [IsInternational]                   BIT              NULL,
    [CustomerType]                      INT              NULL,
    [CompensationTypeId]                UNIQUEIDENTIFIER NULL,
    [ConsignmentId]                     UNIQUEIDENTIFIER NULL,
    [ConNoteNo]                         NVARCHAR (4000)  NULL,
    [AccountId]                         UNIQUEIDENTIFIER NULL,
    [AccountNo]                         NVARCHAR (4000)  NULL,
    [AccountName]                       NVARCHAR (4000)  NULL,
    [SenderName]                        NVARCHAR (4000)  NULL,
    [SenderPhoneNo]                     NVARCHAR (4000)  NULL,
    [SenderEmail]                       NVARCHAR (4000)  NULL,
    [SenderStreet1]                     NVARCHAR (4000)  NULL,
    [SenderStreet2]                     NVARCHAR (4000)  NULL,
    [SenderStreet3]                     NVARCHAR (4000)  NULL,
    [SenderPostCode]                    NVARCHAR (4000)  NULL,
    [SenderCity]                        NVARCHAR (4000)  NULL,
    [SenderStateId]                     UNIQUEIDENTIFIER NULL,
    [SenderStateCode]                   NVARCHAR (4000)  NULL,
    [SenderCountryId]                   UNIQUEIDENTIFIER NULL,
    [SenderCountryCode]                 NVARCHAR (4000)  NULL,
    [ReceiverName]                      NVARCHAR (4000)  NULL,
    [ReceiverPhoneNo]                   NVARCHAR (4000)  NULL,
    [ReceiverEmail]                     NVARCHAR (4000)  NULL,
    [ReceiverStreet1]                   NVARCHAR (4000)  NULL,
    [ReceiverStreet2]                   NVARCHAR (4000)  NULL,
    [ReceiverStreet3]                   NVARCHAR (4000)  NULL,
    [ReceiverPostCode]                  NVARCHAR (4000)  NULL,
    [ReceiverCity]                      NVARCHAR (4000)  NULL,
    [ReceiverStateId]                   UNIQUEIDENTIFIER NULL,
    [ReceiverStateCode]                 NVARCHAR (4000)  NULL,
    [ReceiverCountryId]                 UNIQUEIDENTIFIER NULL,
    [ReceiverCountryCode]               NVARCHAR (4000)  NULL,
    [PaymentMode]                       INT              NULL,
    [PayTo]                             INT              NULL,
    [PayToOthers]                       NVARCHAR (4000)  NULL,
    [BankName]                          NVARCHAR (4000)  NULL,
    [BankAccountNo]                     NVARCHAR (4000)  NULL,
    [ProductId]                         UNIQUEIDENTIFIER NULL,
    [ProductCode]                       NVARCHAR (4000)  NULL,
    [ItemCategoryId]                    UNIQUEIDENTIFIER NULL,
    [ItemCategoryName]                  NVARCHAR (4000)  NULL,
    [NetWeight]                         DECIMAL (19, 5)  NULL,
    [ItemContent]                       NVARCHAR (4000)  NULL,
    [ItemValue]                         DECIMAL (19, 5)  NULL,
    [Charge_Total]                      DECIMAL (19, 5)  NULL,
    [Charge_Courier]                    DECIMAL (19, 5)  NULL,
    [Charge_Fuel]                       DECIMAL (19, 5)  NULL,
    [Charge_Handling]                   DECIMAL (19, 5)  NULL,
    [Charge_ServiceTax]                 DECIMAL (19, 5)  NULL,
    [Charge_OtherAddOns]                DECIMAL (19, 5)  NULL,
    [Charge_InsurancePremium]           DECIMAL (19, 5)  NULL,
    [DeclaredValue]                     DECIMAL (19, 5)  NULL,
    [AcceptedOn]                        DATETIME2 (7)    NULL,
    [DeliveredOn]                       DATETIME2 (7)    NULL,
    [ClaimedOn]                         DATETIME2 (7)    NULL,
    [CrmRefNo]                          NVARCHAR (4000)  NULL,
    [ClaimFor]                          DECIMAL (19, 5)  NULL,
    [Case]                              NVARCHAR (4000)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

