CREATE TABLE [dbo].[Consignment] (
    [Id]                           UNIQUEIDENTIFIER NOT NULL,
    [SerializedSurcharges]         NVARCHAR (4000)  NULL,
    [SerializedValueAddedServices] NVARCHAR (4000)  NULL,
    [ChargeTotal]                  DECIMAL (19, 5)  NULL,
    [BaseRate]                     DECIMAL (19, 5)  NULL,
    [SerializedCharge]             NVARCHAR (4000)  NULL,
    [ConNoteNo]                    NVARCHAR (4000)  NULL,
    [SalesOrderId]                 UNIQUEIDENTIFIER NULL,
    [InvoiceId]                    UNIQUEIDENTIFIER NULL,
    [InvoiceNo]                    NVARCHAR (4000)  NULL,
    [OriginProductCode]            NVARCHAR (4000)  NULL,
    [ProductId]                    UNIQUEIDENTIFIER NULL,
    [ProductCode]                  NVARCHAR (4000)  NULL,
    [ParentProductCode]            NVARCHAR (4000)  NULL,
    [ItemCategoryId]               UNIQUEIDENTIFIER NULL,
    [ItemCategoryName]             NVARCHAR (4000)  NULL,
    [SenderName]                   NVARCHAR (4000)  NULL,
    [SenderPhoneNo]                NVARCHAR (4000)  NULL,
    [SenderEmail]                  NVARCHAR (4000)  NULL,
    [SenderStreet1]                NVARCHAR (4000)  NULL,
    [SenderStreet2]                NVARCHAR (4000)  NULL,
    [SenderStreet3]                NVARCHAR (4000)  NULL,
    [SenderPostCode]               NVARCHAR (4000)  NULL,
    [SenderCity]                   NVARCHAR (4000)  NULL,
    [SenderStateId]                UNIQUEIDENTIFIER NULL,
    [SenderStateCode]              NVARCHAR (4000)  NULL,
    [SenderCountryId]              UNIQUEIDENTIFIER NULL,
    [SenderCountryCode]            NVARCHAR (4000)  NULL,
    [ReceiverName]                 NVARCHAR (4000)  NULL,
    [ReceiverPhoneNo]              NVARCHAR (4000)  NULL,
    [ReceiverEmail]                NVARCHAR (4000)  NULL,
    [ReceiverStreet1]              NVARCHAR (4000)  NULL,
    [ReceiverStreet2]              NVARCHAR (4000)  NULL,
    [ReceiverStreet3]              NVARCHAR (4000)  NULL,
    [ReceiverPostCode]             NVARCHAR (4000)  NULL,
    [ReceiverCity]                 NVARCHAR (4000)  NULL,
    [ReceiverStateId]              UNIQUEIDENTIFIER NULL,
    [ReceiverStateCode]            NVARCHAR (4000)  NULL,
    [ReceiverCountryId]            UNIQUEIDENTIFIER NULL,
    [ReceiverCountryCode]          NVARCHAR (4000)  NULL,
    [ZoneName]                     NVARCHAR (4000)  NULL,
    [Width]                        DECIMAL (19, 5)  NULL,
    [Height]                       DECIMAL (19, 5)  NULL,
    [Length]                       DECIMAL (19, 5)  NULL,
    [ActualWeight]                 DECIMAL (19, 5)  NULL,
    [VolumetricWeight]             DECIMAL (19, 5)  NULL,
    [NetWeight]                    DECIMAL (19, 5)  NULL,
    [ItemContent]                  NVARCHAR (4000)  NULL,
    [ItemValue]                    DECIMAL (19, 5)  NULL,
    [Description]                  NVARCHAR (4000)  NULL,
    [Status]                       INT              NULL,
    [ConsignmentRemarkId]          UNIQUEIDENTIFIER NULL,
    [ProductName]                  NVARCHAR (4000)  NULL,
    [ParentProductName]            NVARCHAR (4000)  NULL,
    [RateId]                       UNIQUEIDENTIFIER NULL,
    [RateRefNo]                    NVARCHAR (4000)  NULL,
    [Pl9No]                        NVARCHAR (4000)  NULL,
    [SalesOrderRefNo]              NVARCHAR (4000)  NULL,
    [Gst]                          DECIMAL (19, 5)  NULL,
    [IsMovable]                    BIT              NULL,
    [GstCode]                      NVARCHAR (4000)  NULL,
    [GLCode]                       NVARCHAR (4000)  NULL,
    [SAPProductCode]               NVARCHAR (4000)  NULL,
    [ChildConNoteNo]               NVARCHAR (255)   NULL,
    [MpsIndicator]                 NVARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

