CREATE TABLE [dbo].[NoteConsignment] (
    [Id]                           UNIQUEIDENTIFIER NOT NULL,
    [NoteId]                       UNIQUEIDENTIFIER NULL,
    [SerializedSurcharges]         NVARCHAR (4000)  NULL,
    [SerializedValueAddedServices] NVARCHAR (4000)  NULL,
    [SerializedCharge]             NVARCHAR (4000)  NULL,
    [ChargeTotal]                  DECIMAL (19, 5)  NULL,
    [OriginalConsignmentId]        UNIQUEIDENTIFIER NULL,
    [OriginalConsignmentNo]        NVARCHAR (4000)  NULL,
    [OriginalChargeTotal]          DECIMAL (19, 5)  NULL,
    [IsRecalculated]               BIT              NULL,
    [ActualWeight]                 DECIMAL (19, 5)  NULL,
    [Length]                       DECIMAL (19, 5)  NULL,
    [Width]                        DECIMAL (19, 5)  NULL,
    [Height]                       DECIMAL (19, 5)  NULL,
    [VolumetricWeight]             DECIMAL (19, 5)  NULL,
    [NetWeight]                    DECIMAL (19, 5)  NULL,
    [SenderPostCode]               NVARCHAR (4000)  NULL,
    [SenderCountryCode]            NVARCHAR (4000)  NULL,
    [ReceiverPostCode]             NVARCHAR (4000)  NULL,
    [ReceiverCountryCode]          NVARCHAR (4000)  NULL,
    [ZoneName]                     NVARCHAR (4000)  NULL,
    [ProductId]                    UNIQUEIDENTIFIER NULL,
    [ItemCategoryId]               UNIQUEIDENTIFIER NULL,
    [Difference]                   DECIMAL (19, 5)  NULL,
    [CorrectionType]               INT              NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

