CREATE TABLE [dbo].[Product] (
    [Id]                           UNIQUEIDENTIFIER NOT NULL,
    [SerializedInputConstraints]   NVARCHAR (4000)  NULL,
    [SerializedItemCategories]     NVARCHAR (4000)  NULL,
    [SerializedSurcharges]         NVARCHAR (4000)  NULL,
    [SerializedValueAddedServices] NVARCHAR (4000)  NULL,
    [Code]                         NVARCHAR (4000)  NULL,
    [Name]                         NVARCHAR (4000)  NULL,
    [Description]                  NVARCHAR (4000)  NULL,
    [PrsCode]                      NVARCHAR (4000)  NULL,
    [SapCode]                      NVARCHAR (4000)  NULL,
    [ParentProductId]              UNIQUEIDENTIFIER NULL,
    [ParentProductCode]            NVARCHAR (4000)  NULL,
    [ValidFrom]                    DATETIME2 (7)    NULL,
    [ValidTo]                      DATETIME2 (7)    NULL,
    [AllowPreferredLane]           BIT              NULL,
    [ApplicableFor]                INT              NULL,
    [GeneralLedgerId]              UNIQUEIDENTIFIER NULL,
    [GeneralLedgerCode]            NVARCHAR (4000)  NULL,
    [PreferredLaneId]              UNIQUEIDENTIFIER NULL,
    [PreferredLaneName]            NVARCHAR (4000)  NULL,
    [SbuId]                        UNIQUEIDENTIFIER NULL,
    [SbuName]                      NVARCHAR (4000)  NULL,
    [IsInternational]              BIT              NULL,
    [Type]                         INT              NULL,
    [ScaleType]                    INT              NULL,
    [Sla]                          TEXT             NULL,
    [CreatedOn]                    DATETIME2 (7)    NULL,
    [CreatedById]                  UNIQUEIDENTIFIER NULL,
    [CreatedByName]                NVARCHAR (4000)  NULL,
    [ParentProductName]            NVARCHAR (4000)  NULL,
    [GeneralLedgerName]            NVARCHAR (4000)  NULL,
    [UpdatedOn]                    DATETIME2 (7)    NULL,
    [UpdatedById]                  UNIQUEIDENTIFIER NULL,
    [UpdatedByName]                NVARCHAR (4000)  NULL,
    [Status]                       INT              NULL,
    [GstCode]                      NVARCHAR (4000)  NULL,
    [KeyFeatured]                  NVARCHAR (4000)  NULL,
	[Ost]				BIT					NULL,
	[MinWeight]			FLOAT			NULL
    PRIMARY KEY CLUSTERED ([Id] ASC), 
    [MaxWeight] FLOAT NULL, 
    [DeliverySla] VARCHAR(255) NULL
);

