CREATE TABLE [dbo].[Registration_noserializedrate] (
    [Id]                        UNIQUEIDENTIFIER NOT NULL,
    [CurrentStage]              INT              NULL,
    [SubmissionResult]          INT              NULL,
    [CreditCheckResult]         INT              NULL,
    [RecommendationResult]      INT              NULL,
    [VerificationResult]        INT              NULL,
    [ApprovalResult]            INT              NULL,
    [FinalResult]               INT              NULL,
    [SalesPersonnelId]          UNIQUEIDENTIFIER NULL,
    [SalesPersonnelName]        NVARCHAR (4000)  NULL,
    [SbuId]                     UNIQUEIDENTIFIER NULL,
    [SbuName]                   NVARCHAR (4000)  NULL,
    [SbuAccountType]            NVARCHAR (4000)  NULL,
    [SkipCreditCheck]           BIT              NULL,
    [CompanyIsBlackListed]      BIT              NULL,
    [CompanyIsCtosListed]       BIT              NULL,
    [BlacklistRemarks]          NVARCHAR (4000)  NULL,
    [DepositAmount]             DECIMAL (19, 5)  NULL,
    [DepositPaid]               BIT              NULL,
    [IsTaxExempted]             BIT              NULL,
    [CreditLimit]               DECIMAL (19, 5)  NULL,
    [CreditRating]              INT              NULL,
    [DocumentCompleted]         BIT              NULL,
    [SubmittedOn]               DATETIME2 (7)    NULL,
    [ApprovedOn]                DATETIME2 (7)    NULL,
    [SerializedRateProposal]    NVARCHAR (4000)  NULL,
    [Category]                  INT              NULL,
    [Channel]                   INT              NULL,
    [RefNo]                     NVARCHAR (4000)  NULL,
    [AccountNo]                 NVARCHAR (4000)  NULL,
    [AccountType]               INT              NULL,
    [SubAccountType]            INT              NULL,
    [BillingType]               INT              NULL,
    [MasterRegistrationId]      UNIQUEIDENTIFIER NULL,
    [MasterRegistrationName]    NVARCHAR (4000)  NULL,
    [IsTempAccount]             BIT              NULL,
    [TempAccountExpiry]         DATETIME2 (7)    NULL,
    [IsAgent]                   BIT              NULL,
    [Name]                      NVARCHAR (4000)  NULL,
    [RocNo]                     NVARCHAR (4000)  NULL,
    [CompanyType]               INT              NULL,
    [IndustryId]                UNIQUEIDENTIFIER NULL,
    [IndustryName]              NVARCHAR (4000)  NULL,
    [IsPostingDomestic]         BIT              NULL,
    [IsPostingInternational]    BIT              NULL,
    [AddressStreet1]            NVARCHAR (4000)  NULL,
    [AddressStreet2]            NVARCHAR (4000)  NULL,
    [AddressStreet3]            NVARCHAR (4000)  NULL,
    [AddressPostCode]           NVARCHAR (4000)  NULL,
    [AddressCity]               NVARCHAR (4000)  NULL,
    [AddressStateName]          NVARCHAR (4000)  NULL,
    [AddressCountryName]        NVARCHAR (4000)  NULL,
    [AddressStateId]            UNIQUEIDENTIFIER NULL,
    [AddressCountryId]          UNIQUEIDENTIFIER NULL,
    [ContactName]               NVARCHAR (4000)  NULL,
    [ContactNric]               NVARCHAR (4000)  NULL,
    [ContactEmail]              NVARCHAR (4000)  NULL,
    [PhoneNo]                   NVARCHAR (4000)  NULL,
    [FaxNo]                     NVARCHAR (4000)  NULL,
    [BillingAddressSame]        BIT              NULL,
    [BillingAddressStreet1]     NVARCHAR (4000)  NULL,
    [BillingAddressStreet2]     NVARCHAR (4000)  NULL,
    [BillingAddressStreet3]     NVARCHAR (4000)  NULL,
    [BillingAddressPostCode]    NVARCHAR (4000)  NULL,
    [BillingAddressCity]        NVARCHAR (4000)  NULL,
    [BillingAddressStateName]   NVARCHAR (4000)  NULL,
    [BillingAddressCountryName] NVARCHAR (4000)  NULL,
    [BillingAddressStateId]     UNIQUEIDENTIFIER NULL,
    [BillingAddressCountryId]   UNIQUEIDENTIFIER NULL,
    [BillingCurrencyId]         UNIQUEIDENTIFIER NULL,
    [BillingCurrencyName]       NVARCHAR (4000)  NULL,
    [PickupAddressStreet1]      NVARCHAR (4000)  NULL,
    [PickupAddressStreet2]      NVARCHAR (4000)  NULL,
    [PickupAddressStreet3]      NVARCHAR (4000)  NULL,
    [PickupAddressPostCode]     NVARCHAR (4000)  NULL,
    [PickupAddressCity]         NVARCHAR (4000)  NULL,
    [PickupAddressStateName]    NVARCHAR (4000)  NULL,
    [PickupAddressCountryName]  NVARCHAR (4000)  NULL,
    [PickupAddressStateId]      UNIQUEIDENTIFIER NULL,
    [PickupAddressCountryId]    UNIQUEIDENTIFIER NULL,
    [PickupContactName]         NVARCHAR (4000)  NULL,
    [PickupContactPhoneNo]      NVARCHAR (4000)  NULL,
    [UpdatedOn]                 DATETIME2 (7)    NULL,
    [BranchId]                  UNIQUEIDENTIFIER NULL,
    [BranchCode]                NVARCHAR (4000)  NULL,
    [HasRateProposal]           BIT              NULL,
    [RateProposalApproved]      BIT              NULL,
    [RateProposalZoneGroupId]   UNIQUEIDENTIFIER NULL,
    [QuotationFileId]           NVARCHAR (4000)  NULL,
    [QuotationFileName]         NVARCHAR (4000)  NULL,
    [DraftComment]              NVARCHAR (4000)  NULL,
    [AccountGroup]              NVARCHAR (4000)  NULL,
    [Name2]                     NVARCHAR (4000)  NULL,
    [GstID]                     NVARCHAR (4000)  NULL,
    [PaymentTermCode]           NVARCHAR (4000)  NULL,
    [CompanyCode]               NVARCHAR (4000)  NULL,
    [DunningProcedure]          NVARCHAR (4000)  NULL,
    [IndustryCode]              NVARCHAR (4000)  NULL,
    [AddressStreet4]            NVARCHAR (4000)  NULL,
    [AddressStreet5]            NVARCHAR (4000)  NULL,
    [AddressStateCode]          NVARCHAR (4000)  NULL,
    [AddressCountryCode]        NVARCHAR (4000)  NULL,
    [BillingAddressStreet4]     NVARCHAR (4000)  NULL,
    [BillingAddressStreet5]     NVARCHAR (4000)  NULL,
    [BillingAddressStateCode]   NVARCHAR (4000)  NULL,
    [BillingAddressCountryCode] NVARCHAR (4000)  NULL,
    [PickupAddressStreet4]      NVARCHAR (4000)  NULL,
    [PickupAddressStreet5]      NVARCHAR (4000)  NULL,
    [PickupAddressStateCode]    NVARCHAR (4000)  NULL,
    [PickupAddressCountryCode]  NVARCHAR (4000)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

