CREATE TABLE [dbo].[Registration] (
    [Id]                        CHAR (36)        NOT NULL,
    [CurrentStage]              INT              NULL,
    [SubmissionResult]          INT              NULL,
    [CreditCheckResult]         INT              NULL,
    [RecommendationResult]      INT              NULL,
    [VerificationResult]        INT              NULL,
    [ApprovalResult]            INT              NULL,
    [FinalResult]               INT              NULL,
    [SalesPersonnelId]          CHAR (36)        NULL,
    [SalesPersonnelName]        VARCHAR (4000)   NULL,
    [SbuId]                     CHAR (36)        NULL,
    [SbuName]                   VARCHAR (4000)   NULL,
    [SbuAccountType]            VARCHAR (4000)   NULL,
    [SkipCreditCheck]           TINYINT          NULL,
    [CompanyIsBlackListed]      TINYINT          NULL,
    [CompanyIsCtosListed]       TINYINT          NULL,
    [BlacklistRemarks]          VARCHAR (4000)   NULL,
    [DepositAmount]             DECIMAL (19, 5)  NULL,
    [DepositPaid]               TINYINT          NULL,
    [IsTaxExempted]             TINYINT          NULL,
    [CreditLimit]               DECIMAL (19, 5)  NULL,
    [CreditRating]              INT              NULL,
    [DocumentCompleted]         TINYINT          NULL,
    [SubmittedOn]               VARCHAR (27)     NULL,
    [ApprovedOn]                DATETIME2 (7)    NULL,
    [SerializedRateProposal]    VARCHAR (4000)   NULL,
    [Category]                  INT              NULL,
    [Channel]                   INT              NULL,
    [RefNo]                     VARCHAR (4000)   NULL,
    [AccountNo]                 VARCHAR (4000)   NULL,
    [AccountType]               INT              NULL,
    [SubAccountType]            INT              NULL,
    [BillingType]               INT              NULL,
    [MasterRegistrationId]      CHAR (36)        NULL,
    [MasterRegistrationName]    VARCHAR (4000)   NULL,
    [IsTempAccount]             TINYINT          NULL,
    [TempAccountExpiry]         VARCHAR (27)     NULL,
    [IsAgent]                   TINYINT          NULL,
    [Name]                      VARCHAR (4000)   NULL,
    [RocNo]                     VARCHAR (4000)   NULL,
    [CompanyType]               INT              NULL,
    [IndustryId]                CHAR (36)        NULL,
    [IndustryName]              VARCHAR (4000)   NULL,
    [IsPostingDomestic]         TINYINT          NULL,
    [IsPostingInternational]    TINYINT          NULL,
    [AddressStreet1]            VARCHAR (4000)   NULL,
    [AddressStreet2]            VARCHAR (4000)   NULL,
    [AddressStreet3]            VARCHAR (4000)   NULL,
    [AddressPostCode]           VARCHAR (4000)   NULL,
    [AddressCity]               VARCHAR (4000)   NULL,
    [AddressStateName]          VARCHAR (4000)   NULL,
    [AddressCountryName]        VARCHAR (4000)   NULL,
    [AddressStateId]            CHAR (36)        NULL,
    [AddressCountryId]          CHAR (36)        NULL,
    [ContactName]               VARCHAR (4000)   NULL,
    [ContactNric]               VARCHAR (4000)   NULL,
    [ContactEmail]              VARCHAR (4000)   NULL,
    [PhoneNo]                   VARCHAR (4000)   NULL,
    [FaxNo]                     VARCHAR (4000)   NULL,
    [BillingAddressSame]        TINYINT          NULL,
    [BillingAddressStreet1]     VARCHAR (4000)   NULL,
    [BillingAddressStreet2]     VARCHAR (4000)   NULL,
    [BillingAddressStreet3]     VARCHAR (4000)   NULL,
    [BillingAddressPostCode]    VARCHAR (4000)   NULL,
    [BillingAddressCity]        VARCHAR (4000)   NULL,
    [BillingAddressStateName]   VARCHAR (4000)   NULL,
    [BillingAddressCountryName] VARCHAR (4000)   NULL,
    [BillingAddressStateId]     CHAR (36)        NULL,
    [BillingAddressCountryId]   CHAR (36)        NULL,
    [BillingCurrencyId]         CHAR (36)        NULL,
    [BillingCurrencyName]       VARCHAR (4000)   NULL,
    [PickupAddressStreet1]      VARCHAR (4000)   NULL,
    [PickupAddressStreet2]      VARCHAR (4000)   NULL,
    [PickupAddressStreet3]      VARCHAR (4000)   NULL,
    [PickupAddressPostCode]     VARCHAR (4000)   NULL,
    [PickupAddressCity]         VARCHAR (4000)   NULL,
    [PickupAddressStateName]    VARCHAR (4000)   NULL,
    [PickupAddressCountryName]  VARCHAR (4000)   NULL,
    [PickupAddressStateId]      CHAR (36)        NULL,
    [PickupAddressCountryId]    CHAR (36)        NULL,
    [PickupContactName]         VARCHAR (4000)   NULL,
    [PickupContactPhoneNo]      VARCHAR (4000)   NULL,
    [UpdatedOn]                 VARCHAR (27)     NULL,
    [BranchId]                  CHAR (36)        NULL,
    [BranchCode]                VARCHAR (4000)   NULL,
    [HasRateProposal]           TINYINT          NULL,
    [RateProposalApproved]      TINYINT          NULL,
    [RateProposalZoneGroupId]   CHAR (36)        NULL,
    [QuotationFileId]           VARCHAR (4000)   NULL,
    [QuotationFileName]         VARCHAR (4000)   NULL,
    [DraftComment]              VARCHAR (4000)   NULL,
    [AccountGroup]              VARCHAR (4000)   NULL,
    [Name2]                     VARCHAR (4000)   NULL,
    [GstID]                     VARCHAR (4000)   NULL,
    [PaymentTermCode]           VARCHAR (4000)   NULL,
    [CompanyCode]               VARCHAR (4000)   NULL,
    [DunningProcedure]          VARCHAR (4000)   NULL,
    [IndustryCode]              VARCHAR (4000)   NULL,
    [AddressStreet4]            VARCHAR (4000)   NULL,
    [AddressStreet5]            VARCHAR (4000)   NULL,
    [AddressStateCode]          VARCHAR (4000)   NULL,
    [AddressCountryCode]        VARCHAR (4000)   NULL,
    [BillingAddressStreet4]     VARCHAR (4000)   NULL,
    [BillingAddressStreet5]     VARCHAR (4000)   NULL,
    [BillingAddressStateCode]   VARCHAR (4000)   NULL,
    [BillingAddressCountryCode] VARCHAR (4000)   NULL,
    [PickupAddressStreet4]      VARCHAR (4000)   NULL,
    [PickupAddressStreet5]      VARCHAR (4000)   NULL,
    [PickupAddressStateCode]    VARCHAR (4000)   NULL,
    [PickupAddressCountryCode]  VARCHAR (4000)   NULL,
    [CreditOfficerId]           UNIQUEIDENTIFIER NULL,
    [CreditOfficerName]         NVARCHAR (4000)  NULL,
    [ContactMobile]             NVARCHAR (4000)  NULL
);

