
                
                    create view [dbo].[SalesOrderConsignment] as 
                        select 
                            coalesce(c.Id, s.Id) as Id,

                            s.Id as SalesOrderId,
                            s.RefNo,
                            s.AccountId,
                            s.AccountNo,
                            s.AccountName,
                            s.MasterAccountNo,
                            s.GroupId,
                            s.BranchId,
                            s.BranchCode,
                            s.BranchName,
                            s.ProfitCentreCode,
                            s.Pl9No,
                            s.CreatedOn,
                            s.UpdatedOn,
                            s.AcceptanceOriginId,
                            s.AcceptanceOriginName,
                            s.AcceptedOn,
                            s.Status as SalesOrderStatus,
							s.InvoiceNo,

                            c.Id as ConsignmentId,
                            c.ConNoteNo,
                            c.OriginProductCode,
                            c.ProductId,
                            c.ProductCode,
                            c.ParentProductCode,
                            c.ItemCategoryId,
                            c.SenderName,
                            c.SenderPhoneNo,
                            c.SenderEmail,
                            c.SenderStreet1,
                            c.SenderStreet2,
                            c.SenderStreet3,
                            c.SenderPostCode,
                            c.SenderCity,
                            c.SenderStateId,
                            c.SenderCountryId,
                            c.ReceiverName,
                            c.ReceiverPhoneNo,
                            c.ReceiverEmail,
                            c.ReceiverStreet1,
                            c.ReceiverStreet2,
                            c.ReceiverStreet3,
                            c.ReceiverPostCode,
                            c.ReceiverCity,
                            c.ReceiverStateId,
                            c.ReceiverCountryId,
                            c.ZoneName,
                            c.Width,
                            c.Height,
                            c.Length,
                            c.ActualWeight,
                            c.VolumetricWeight,
                            c.NetWeight,
                            c.BaseRate,
                            c.ChargeTotal,
                            c.ItemContent,
                            c.ItemValue,
                            c.Status as ConsignmentStatus,
                            c.ConsignmentRemarkId

                            from SalesOrder s
                                left join Consignment c on s.Id=c.SalesOrderId

